source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SMHTTPClient_Tests', :exclusive => true do
  pod "SMHTTPClient", :path => "../"

  pod "GCDWebServer"
  pod 'Quick'
  pod 'Nimble'
end
