# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install
script:
- pwd
- ls
- xcodebuild -workspace SMHTTPClient.xcworkspace -list
- set -o pipefail && xcodebuild test -workspace SMHTTPClient.xcworkspace -scheme SMHTTPClient -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
osx_image: xcode7.1
